apiVersion: apps/v1
kind: Deployment
metadata:
  name: say-hi-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: say-hi-operator
  template:
    metadata:
      labels:
        name: say-hi-operator
    spec:
      serviceAccountName: say-hi-operator
      containers:
        - name: say-hi-operator
          # Replace this with the built image name
          image: claudioed/say-hi-operator
          command:
          - say-hi-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "say-hi-operator"
